config/routes.rb
Rails.application.routes.draw do
  
  root to: 'homes#top'
  get 'about' => 'homes#about'
  
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }
  
  resources :customers do
    member do
      get :follows, :followers
    end
      resource :relationships, only: [:create, :destroy]
  end
  resources :posts
  get '/favicon.ico', to: redirect('/path/to/favicon.ico')
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  
  has_many :followers, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followeds, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  
  has_many :following_customers, through: :followers, source: :followed
  has_many :follower_customers, through: :followeds, source: :follower
  
def follow(customer_id)
  followers.create(followed_id: customer_id)
end

#　フォローを外すときの処理
def unfollow(customer_id)
  followers.find_by(followed_id: customer_id).destroy
end

#フォローしていればtrueを返す
def following?(customer)
  following_customers.include?(customer)
end	 
  
  
  
  validates :name, uniqueness: true
  validates :name, presence: true, length: { in: 2..20 }
         
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
    @customer = current_customer
    @post = Post.new
  end

  def show
    @customer = Customer.find(params[:id])
    @posts = @customer.posts
    @following_customers = @customer.following_customers
    @follower_customers = @customer.follower_customers
    @post = Post.new
  end

  def edit
    customer = Customer.find(params[:id])
    unless customer.id == current_customer.id
      redirect_to customer_path(current_customer.id)
    end
    @customer = Customer.find(params[:id])
  end
  
  def update
    customer = Customer.find(params[:id])
    unless customer.id == current_customer.id
      redirect_to customer_path(current_customer.id)
    end
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to customer_path(@customer.id)
    else
      render :edit
    end
  end
  
  def follows
    customer = Customer.find(params[:id])
    @customer = customer.following_customers
  end

  def followers
   customer = Customer.find(params[:id])
    @customer = customer.follower_customers
  end

  
  private
  def customer_params
    params.require(:customer).permit(:name, :introduction)
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>ユーザー詳細編集</h1>
      <% if @customer.errors.any? %>
        <%= @customer.errors.count %>errors prohibited this obj from being saved:
        <ul>
          <% @customer.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>

        <%= form_with model: @customer do |f| %>
          <div class="form-group">
            <h5 for="inputName">Name</h5>
            <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"Name"%>
          </div>
          
          <div class="form-group">
            <h5>Introduction</h5>
            <%= f.text_area :introduction %>
          </div>

          <div class="form-group "><%= f.submit '保存', class: 'btn btn-secondary' %></div>
        <% end %>
    </div>
  </div>
</div>

app/views/customers/followers.html.erb
<h2>フォロワー</h2>
  <table class='table'>
    <tbody>
      <% @customer.each do |customer| %>
        <tr>
          <td><%= customer.name %></td>
          <td>
            <%= link_to follows_customer_path(customer) do %>
              <p>フォロー<%= customer.followers.count %></p>
            <% end %>
          </td>
          <td>  
            <%= link_to followers_customer_path(customer) do %>
              <p>フォロワー<%= customer.followeds.count %></p>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table> 

app/views/customers/follows.html.erb
<h2>フォロー</h2>
  <table class='table'>
    <tbody>
      <% @customer.each do |customer| %>
        <tr>
          <td><%= customer.name %></td>
          <td>
            <%= link_to follows_customer_path(customer) do %>
              <p>フォロー<%= customer.followers.count %></p>
            <% end %>
          </td>
          <td>  
            <%= link_to followers_customer_path(customer) do %>
              <p>フォロワー<%= customer.followeds.count %></p>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table> 

app/views/customers/index.html.erb
<div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-8 offset-md-1">
        <h1>ユーザー一覧</h1>
          <table class="table table-hover table-inverse">
            <tbody>
              <tr>
              <% @customers.each do |customer| %>
                <td><%= link_to customer.name, customer_path(customer.id) %></td>
                <td><%= customer.introduction %></td>
                <td>フォロー<%= customer.followers.count %></td>
                <td>フォロワー<%= customer.followeds.count %></td>
                <td>
                  <% if current_customer != customer %>
                    <% if current_customer.following?(customer) %>
                      <%= link_to "フォロー外す", customer_relationships_path(customer.id), method: :delete, class: "btn btn-danger" %>
                    <% else %>
                      <%= link_to "フォローする", customer_relationships_path(customer.id), method: :post, class:"btn btn-success" %>
                    <% end %>
                  <% end %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
      </div>
    </div>
</div>

app/views/customers/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User Info</h2>
        <table class="table">
          <tbody>
            <tr></tr>
            <tr>
              <th>Name</th>
              <th><%= @customer.name %></th>
            </tr>
            <tr>
              <th>Introduction</th>
              <th><%= @customer.introduction %></th>
            </tr>
            <tr>
              <th>フォロー</th>
              <th><%= link_to follows_customer_path(@customer) do %>
              <%= @customer.followers.count %></th>
              <% end %>
            </tr>
            <tr>
              <th>フォロワー</th>
              <th><%= link_to followers_customer_path(@customer) do %>
                <%= @customer.followeds.count %></th>
              <% end %>
            </tr>
          </tbody>
        </table>
        <div class="row">
          <% if current_customer != @customer %>
            <% if current_customer.following?(@customer) %>
              <%= link_to "フォロー外す", customer_relationships_path(@customer.id), method: :delete, class: "btn btn-danger" %>
            <% else %>
              <%= link_to "フォローする", customer_relationships_path(@customer.id), method: :post, class:"btn btn-success" %>
            <% end %>
          <% end %>
          
          <%= link_to edit_customer_path(@customer), class: 'btn btn-outline-secondary btn-block' do %>
            <i class="fas fa-user-cog" aria-hidden="true"></i>
          <% end %>
        </div>
      <%= render 'posts/new', post: @post %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h1>Records</h1>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>Title</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <% @posts.each do |post| %>
            <th><h3><strong><%= link_to post.title, post_path(post.id) %></strong></h3><%= post.created_at.strftime('%Y/%m/%d') %></th>
          </tr>
            <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>