config/routes.rb
Rails.application.routes.draw do
  
  root to: 'homes#top'
  get 'about' => 'homes#about'
  
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }
  
  resources :customers do
    member do
      get :follows, :followers
    end
      resource :relationships, only: [:create, :destroy]
  end
  resources :posts
  get '/favicon.ico', to: redirect('/path/to/favicon.ico')
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gamesrecord</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <script src="https://kit.fontawesome.com/af84ec0176.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand mr-auto p-2 bd-highlight" href="/"><sapn>Gamesrecord</sapn></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                    aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse show navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav ml-auto">
                <% if customer_signed_in? %>
                  <li>
                    <%= link_to customer_path(current_customer.id), class: 'nav-link text-ligth'  do %>
                     <i class="fas fa-home"></i>Mypage
                    <% end %>
                  </li>
                  <li>
                    <%= link_to customers_path, class: 'nav-link text-ligth' do %>
                    <i class="fa-solid fa-users"></i>Users
                    <% end %>
                  </li>
                  <li>
                    <%= link_to posts_path, class: 'nav-link text-ligth' do %>
                    <i class="fa-solid fa-book-open"></i>Records
                    <% end %>
                  </li>
                  <li>
                    <%= link_to destroy_customer_session_path, method: :delete, class: 'nav-link text-ligth' do %>
                    <i class="fas fa-sign-out-alt"></i>Log out
                    <% end %>
                  </li>
                <% else %>
                  <li>
                    <%= link_to root_path, class: 'nav-link text-ligth' do %>
                    <i class="fas fa-home"></i>Home
                    <% end %>
                  </li>
                  <li>
                    <%= link_to about_path, class: 'nav-link text-ligth' do %>
                    <i class="fa-solid fa-link"></i>About
                    <% end %>
                  </li>
                  <li>
                    <%= link_to new_customer_registration_path, class: 'nav-link text-ligth' do %>
                    <i class="fa-solid fa-user-plus"></i>Sign up
                    <% end %>
                  </li>
                  <li>
                    <%= link_to new_customer_session_path, class: 'nav-link text-ligth' do %>
                    <i class="fas fa-sign-in-alt"></i>Log in
                    <% end %>
                  </li>
                <% end %>
              </ul>
            </div>
        </div>
      </nav>
    </header>
    <main>
      <p id="notice"></p>
    <div>
      <%= flash[:notice] %>
    </div>
    <%= yield %>
    </main>
  </body>
</html>